name = "shonan-doors-external-watchdog"
main = "src/index.js"
compatibility_date = "2026-10-01"

[triggers]
crons = ["7,37 20-23 * * *", "7,37 0-12 * * *"]

[vars]
GITHUB_REPO = "sysywq/shonan-doors"
