name = "shonan-doors-external-watchdog"
main = "src/index.js"
compatibility_date = "2026-10-01"

[triggers]
crons = ["7,22,37,52 19-23 * * *", "7,22,37,52 0-12 * * *"]

[vars]
GITHUB_REPO = "sysywq/shonan-doors"
